### ISSUE TITLE
"Event name is missing" is misleading

### ISSUE THREAD

**Issue by lorenzleutgeb** [thenativeweb/commands-events#2]
I wasted quite some time checking whether I populate my event's name correctly when I received ["Event name is missing"](https://github.com/thenativeweb/commands-events/blob/d2d8c0052a2413d82c40d8ed98781ea166bcf8c7/dist/Event.js#L41). It turned out that the name was not *missing* but just *not alphanumeric* (since I used the `_` symbol as part of my event name).

Please change this error message to say something along the lines "Event name is missing or not alphanumeric". This might save other users of this library from wasting their time like me. Thank you.

Actually, you might consider changing `formats` to deliver more fine grained error messages...

**Comment by goloroden** [comment]
Hi @lorenzleutgeb 😊 

I just wanted to get back to you and let you know that I have fixed this issue now. The error messages are now different for missing parameters and parameters of the wrong type.

The changes have already been published and pushed to npm. Once you install the new version `1.0.2`, your problems should be gone 😊

Regarding your suggestion of adjusting `formats`: Yes, that's a good suggestion as well. Do you have any specific ideas here? If so, it would be great if you could let us know. Maybe an issue in the [formats repository](https://github.com/thenativeweb/formats) makes sense for this.
